{% set version = '0.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-checkhelper
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/checkhelper_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/checkhelper/checkhelper_{{ version }}.tar.gz
  sha256: bfeeff2b4eb1f5141cccd4d1cc7179bfd0de684cc2d3338543c906559f871952

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-desc
    - r-devtools
    - r-dplyr
    - r-glue
    - r-lifecycle
    - r-magrittr
    - r-pkgbuild
    - r-purrr
    - r-rcmdcheck
    - r-roxygen2
    - r-stringr
    - r-whisker >=0.4
    - r-withr
  run:
    - r-base
    - r-cli
    - r-desc
    - r-devtools
    - r-dplyr
    - r-glue
    - r-lifecycle
    - r-magrittr
    - r-pkgbuild
    - r-purrr
    - r-rcmdcheck
    - r-roxygen2
    - r-stringr
    - r-whisker >=0.4
    - r-withr

test:
  commands:
    - $R -e "library('checkhelper')"           # [not win]
    - "\"%R%\" -e \"library('checkhelper')\""  # [win]

about:
  home: https://github.com/ThinkR-open/checkhelper
  doc_url: https://thinkr-open.github.io/checkhelper/
  license: MIT
  summary: Deal with packages 'check' outputs and reduce the risk of rejection by 'CRAN' by following
    policies.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: checkhelper
# Title: Deal with Check Outputs
# Version: 0.1.1
# Authors@R: c( person("Sebastien", "Rochette", , "sebastien@thinkr.fr", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-1565-9313")), person("Vincent", "Guyader", , "vincent@thinkr.fr", role = "aut", comment = c(ORCID = "0000-0003-0671-9270")), person("Arthur", "Breant", , "arthur@thinkr.fr", role = "aut", comment = c(ORCID = "0000-0003-1668-0963")), person("Murielle", "Delmotte", , "murielle@thinkr.fr", role = "aut", comment = c(ORCID = "0000-0002-1339-2424")), person("ThinkR", role = "cph") )
# Description: Deal with packages 'check' outputs and reduce the risk of rejection by 'CRAN' by following policies.
# License: MIT + file LICENSE
# URL: https://thinkr-open.github.io/checkhelper/, https://github.com/ThinkR-open/checkhelper
# BugReports: https://github.com/ThinkR-open/checkhelper/issues
# Depends: R (>= 2.10)
# Imports: cli, desc, devtools, dplyr, glue, lifecycle, magrittr, pkgbuild, purrr, rcmdcheck, roxygen2, stringr, tools, utils, whisker (>= 0.4), withr
# Suggests: attachment, callr, knitr, rmarkdown, testthat, usethis
# VignetteBuilder: knitr
# Config/fusen/version: 0.5.0.9009
# Config/Needs/website: ThinkR-open/thinkrtemplate
# Encoding: UTF-8
# Language: en-US
# RoxygenNote: 7.3.0
# NeedsCompilation: no
# Packaged: 2024-01-22 08:39:34 UTC; murielle
# Author: Sebastien Rochette [aut, cre] (<https://orcid.org/0000-0002-1565-9313>), Vincent Guyader [aut] (<https://orcid.org/0000-0003-0671-9270>), Arthur Breant [aut] (<https://orcid.org/0000-0003-1668-0963>), Murielle Delmotte [aut] (<https://orcid.org/0000-0002-1339-2424>), ThinkR [cph]
# Maintainer: Sebastien Rochette <sebastien@thinkr.fr>
# Repository: CRAN
# Date/Publication: 2024-01-22 09:22:46 UTC
